config/routes.rb
Rails.application.routes.draw do

  get 'queries/new'
  get 'query', to: 'queries#result_display'
  post 'query/destroy', to: 'queries#destroy'
  get 'queries', to: 'queries#index'
  post 'queries/create'
  post 'visit_update/:id', to: 'queries#update_results_visit'
  post 'benefits/fetch'
  get 'admin/index'
  get 'admin/new_password'
  post 'admin/update_password'
  get 'admin/destroy'
  get 'about', to: 'app_info#about_app'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'queries#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
end

app/models/province_code.rb
class ProvinceCode < ApplicationRecord
  has_many :queries
end

app/models/query.rb
class Query < ApplicationRecord
  has_many :user_queries, dependent: :destroy
  has_many :users, through: :user_queries
  has_many :query_results, dependent: :destroy
  has_many :results, through: :query_results
  #belongs_to :province_code, foreign_key: :province

  validates :benefit, uniqueness: { scope: [:benefit, :province, :locality, :case ] }
  validates :benefit, :locality, :case, :province, presence: true

  before_validation :capitalize_parameters, on: :create

  PROVINCE_CODES = {
    "01" => "Dolnośląskie",
    "02" => "Kujawsko-pomorskie",
    "03" => "Lubelskie",
    "04" => "Lubuskie",
    "05" => "Łódzkie",
    "06" => "Małopolskie",
    "07" => "Mazowieckie",
    "08" => "Opolskie",
    "09" => "Podkarpackie",
    "10" => "Podlaskie",
    "11" => "Pomorskie",
    "12" => "Śląskie",
    "13" => "Świętokrzyskie",
    "14" => "Warmińsko-mazurskie",
    "15" => "Wielkopolskie",
    "16" => "Zachodnio-pomorskie"
  }

  def decode_province!
    self.province = PROVINCE_CODES.fetch(self.province)
    self
  end

  private
  
    def capitalize_parameters
      self.locality = locality.capitalize
      self.benefit = benefit.capitalize
    end
end

app/models/query_result.rb
class QueryResult < ApplicationRecord
  belongs_to :query
  belongs_to :result

end

app/models/result.rb
class Result < ApplicationRecord
  has_many :query_results, dependent: :destroy
  has_many :queries, through: :query_results

  validates :benefit, uniqueness: { scope: [:provider, :place, :address] }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :validatable,
         :confirmable
         
  has_many :user_queries, dependent: :destroy
  has_many :queries, through: :user_queries
 
end

app/models/user_query.rb
class UserQuery < ApplicationRecord
  belongs_to :user
  belongs_to :query

  validates :user_id, uniqueness: { scope: :query_id }
  validates :user_id, :query_id , presence: true

  before_destroy do
    @query = self.query
  end

  after_destroy do
    @query.destroy unless @query.user_queries.any?
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin_check

  def index
    @users = User.all
  end

  def new_password
    @user = User.find(params[:id])
  end

  def update_password
    user = User.find(params[:id])
    user.password = params[:new_password]
    if user.save
      redirect_to admin_index_path
    else
      flash[:alert] = user.errors.full_messages
      redirect_to admin_new_password_path(id: user.id)
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_index_path
  end

  private

    def admin_check
      redirect_to authenticated_root_path if !current_user.admin?
    end
end

app/controllers/app_info_controller.rb
class AppInfoController < ApplicationController

  def about_app
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController

  def fetch
    response = HTTParty.get('https://api.nfz.gov.pl/app-itl-api/benefits?limit=25')
    p response.body
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  def index
    @queries = current_user.queries.order(:created_at).includes(:results, :user_queries).paginate(page: params[:page], per_page: 10)
    @queries.each { |q| q.decode_province! }
    #@user_queries = current_user.queries.includes(:province_code)
  end

  def result_display
    @query = Query.find(params[:id]).decode_province!
    @user_query = current_user.user_queries.find_by(query_id: params[:id])
    @query_results = @query.results.order("date")
  end

  def new
  end

  def create
    permitted_params = query_params
    if params.values.any?(&:empty?)
      flash[:warning] = "Oba pola muszą być wypełnione"
      redirect_to queries_new_path and return
    end
    permitted_params.each_value { |p| p.capitalize! }
    query = Query.find_by(permitted_params)
    if query.nil?
      query = Query.create(permitted_params)
      InitialSearch.call(query.id)
    end
    query.user_queries.create(user_id: current_user.id)
    redirect_to query_path(id: query.id)
  end

  def destroy
    current_user.user_queries.find_by(query_id: params[:id]).destroy
    redirect_to queries_path
  end

  def update_results_visit
    user_query = UserQuery.find(params[:id])
    user_query.update_attribute(:visited_results_at, Time.zone.now)
  end

  private

    def query_params
      params.permit(:case, :province, :locality, :benefit)
    end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/app_info_helper.rb
module AppInfoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/query_helper.rb
module QueryHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h2>Użytkownicy</h2>
<%= render partial: 'shared/user', collection: @users %>

app/views/admin/new_password.html.erb
<div class="header">
  <h2>Zmień hasło użytkownika <%= @user.email %></h2>
</div>

<%= form_with url: admin_update_password_path, method: :post do |f| %>
  <%= render 'shared/flash_alert' %>

  <div class="form-group">
    <%= f.text_field :new_password, placeholder: "Nowe hasło" %>
  </div>

  <div class="form-group button">
    <%= f.submit "Zapisz" %>
  </div>
  <%= f.hidden_field :id, value: params[:id] %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NFZAlert</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :meta %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :script %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="main-box">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_alert.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <% if flash[:alert].class == String %>
      <%= flash[:alert] %>
    <% else %>
      <% flash[:alert].each do |msg| %>
        <%= msg %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_mailer_result.html.erb
<div class="mail-result-box">
  <div>
    <p><strong>Najbliższy termin wizyty:</strong></p>
    <p><%= mailer_result.date.to_datetime.strftime("%-d.%m.%Y") %></p><br>
    <p>
      <strong><%= mailer_result.benefit %></strong>
    </p>
    <p><%= mailer_result.provider %></p>
    <p><%= mailer_result.place %></p>
    <p><strong>Adres:</strong> <%= mailer_result.locality%>, <%= mailer_result.address %></p>
    <p><strong>Tel.</strong> <%= mailer_result.phone %></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <ul class="navbar-nav">
    <% if current_user %>
      <li class="nav-item active"><%= link_to 'Wyszukiwania', queries_path, class: "text-white nav-link" %></li>
      <% if current_user && current_user.admin? %>
        <li class="nav-item active"><%= link_to('Panel administratora', admin_index_path, method: :get, class: "text-white nav-link")%></li>
      <% end %>
    <% else %>
      <li class="nav-item active"><%= link_to('Zaloguj się', new_user_session_path, method: :get, class: "text-white nav-link")%></li>
      <li class="nav-item active"><%= link_to('O aplikacji', about_path, method: :get, class: "text-white nav-link")%></li>
    <% end %>
  </ul>
  <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li>  
        <div class="dropdown show">
          <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Moje konto
          </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" rel="nofollow" data-method="get" href="/about">Edycja konta</a>
          <a class="dropdown-item" rel="nofollow" href="/about">O aplikacji</a>
          <a class="dropdown-item" rel="nofollow" data-method="delete" href="/users/sign_out">Wyloguj się</a>
        </div>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_pagination.html.erb
<div class="digg_pagination">
  <%= will_paginate resource, next_label: "Następna", previous_label: "Poprzednia" %>
</div>

app/views/shared/_query.html.erb
<div class="query-box">
  <div class="col-5">
    <p>
      Świadczenie: <strong><%= query.benefit %></strong>
      <% if query.case == 2 %>
        <strong>, pilny przypadek</strong>
      <% end %>
    </p>
    <p>Miejscowość: <strong><%= query.locality%></strong></p>
    <p>Województwo: <strong><%= query.province %></strong></p>
  </div>
  <div class="col-4">
    <p>Data utworzenia: <strong><%= query.user_queries.find { |q| q.user_id == current_user.id }.
    created_at.strftime("%-d.%m.%Y") %></strong></p>
    <p>Liczba dostępnych terminów: <strong><%= query.results.size %></strong>
    <p>Najbliższe terminy: 
      <% unless query.results.empty? %>
        <strong>
          <%= query.results.map { |r| r.date }.uniq.sort[0..1].map { |d| d.to_datetime.strftime('%-d.%m.%y') }.join(', ') %>
        </strong>
      <% else %>
        <strong>Brak wyników</strong>
      <% end %>
    </p>
  </div>
  <div class="col-3 text-right">
    <div id="results-button"><%= button_to "Wyniki", query_path, method: :get, params: { id: query.id } %></div>
    <div id="destroy-button"><%= button_to "Usuń", query_destroy_path, params: { id: query.id }, data: { confirm: "Czy na pewno chcesz to usunąć? "} %></div>
  </div>
</div>

app/views/shared/_result.html.erb
<div class="result-box">
  <div class="col-8">
    <p>
      <strong><%= result.benefit %></strong>
    </p>
    <p><%= result.provider %></p>
    <p><%= result.place %></p>
    <p><strong>Adres:</strong> <%= result.locality%>, <%= result.address %></p>
    <p><strong>Tel.</strong> <%= result.phone %></p>
  </div>
  <div class="col-4 text-right"> 
    <p><strong>Najbliższy termin wizyty:</strong></p>
    <p><%= result.date.to_datetime.strftime("%-d.%m.%Y") %></p>
    <% if result.created_at > @user_query.visited_results_at %>
      <div class="new-info">NOWY</div>
    <% end %>
  </div>

</div>

app/views/shared/_user.html.erb
<p>
  <% if user != current_user %>
    <%= user.email %>
    <%= link_to "Zmień hasło", admin_new_password_path(id: user.id) %>
    <%= link_to "Usuń", admin_destroy_path(id: user.id), data: {confirm: "Czy na pewno?"} %>
  <% end %>
</p>