config/routes.rb
Rails.application.routes.draw do

  get 'queries/new'
  get 'query', to: 'queries#result_display'
  post 'query/destroy', to: 'queries#destroy'
  get 'queries', to: 'queries#index'
  post 'queries/create'
  post 'visit_update/:id', to: 'queries#update_results_visit'
  post 'benefits/fetch'
  get 'admin/index'
  get 'admin/new_password'
  post 'admin/update_password'
  get 'admin/destroy'
  get 'about', to: 'app_info#about_app'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'queries#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
end

app/models/province_code.rb
class ProvinceCode < ApplicationRecord
  has_many :queries
end

app/models/query.rb
class Query < ApplicationRecord
  has_many :user_queries, dependent: :destroy
  has_many :users, through: :user_queries
  has_many :query_results, dependent: :destroy
  has_many :results, through: :query_results
  #belongs_to :province_code, foreign_key: :province

  validates :benefit, uniqueness: { scope: [:benefit, :province, :locality, :case ] }
  validates :benefit, :locality, :case, :province, presence: true

  before_validation :capitalize_parameters, on: :create

  PROVINCE_CODES = {
    "01" => "Dolnośląskie",
    "02" => "Kujawsko-pomorskie",
    "03" => "Lubelskie",
    "04" => "Lubuskie",
    "05" => "Łódzkie",
    "06" => "Małopolskie",
    "07" => "Mazowieckie",
    "08" => "Opolskie",
    "09" => "Podkarpackie",
    "10" => "Podlaskie",
    "11" => "Pomorskie",
    "12" => "Śląskie",
    "13" => "Świętokrzyskie",
    "14" => "Warmińsko-mazurskie",
    "15" => "Wielkopolskie",
    "16" => "Zachodnio-pomorskie"
  }

  def decode_province!
    self.province = PROVINCE_CODES.fetch(self.province)
    self
  end

  private
  
    def capitalize_parameters
      self.locality = locality.capitalize
      self.benefit = benefit.capitalize
    end
end

app/models/query_result.rb
class QueryResult < ApplicationRecord
  belongs_to :query
  belongs_to :result

end

app/models/result.rb
class Result < ApplicationRecord
  has_many :query_results, dependent: :destroy
  has_many :queries, through: :query_results

  validates :benefit, uniqueness: { scope: [:provider, :place, :address] }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :validatable,
         :confirmable
         
  has_many :user_queries, dependent: :destroy
  has_many :queries, through: :user_queries
 
end

app/models/user_query.rb
class UserQuery < ApplicationRecord
  belongs_to :user
  belongs_to :query

  validates :user_id, uniqueness: { scope: :query_id }
  validates :user_id, :query_id , presence: true

  before_destroy do
    @query = self.query
  end

  after_destroy do
    @query.destroy unless @query.user_queries.any?
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin_check

  def index
    @users = User.all
  end

  def new_password
    @user = User.find(params[:id])
  end

  def update_password
    user = User.find(params[:id])
    user.password = params[:new_password]
    if user.save
      redirect_to admin_index_path
    else
      flash[:alert] = user.errors.full_messages
      redirect_to admin_new_password_path(id: user.id)
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_index_path
  end

  private

    def admin_check
      redirect_to authenticated_root_path if !current_user.admin?
    end
end

app/controllers/app_info_controller.rb
class AppInfoController < ApplicationController

  def about_app
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController

  def fetch
    response = HTTParty.get('https://api.nfz.gov.pl/app-itl-api/benefits?limit=25')
    p response.body
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  def index
    @queries = current_user.queries.order(:created_at).includes(:results, :user_queries).paginate(page: params[:page], per_page: 10)
    @queries.each { |q| q.decode_province! }
    #@user_queries = current_user.queries.includes(:province_code)
  end

  def result_display
    @query = Query.find(params[:id]).decode_province!
    @user_query = current_user.user_queries.find_by(query_id: params[:id])
    @query_results = @query.results.order("date")
  end

  def new
  end

  def create
    permitted_params = query_params
    if params.values.any?(&:empty?)
      flash[:warning] = "Oba pola muszą być wypełnione"
      redirect_to queries_new_path and return
    end
    permitted_params.each_value { |p| p.capitalize! }
    query = Query.find_by(permitted_params)
    if query.nil?
      query = Query.create(permitted_params)
      InitialSearch.call(query.id)
    end
    query.user_queries.create(user_id: current_user.id)
    redirect_to query_path(id: query.id)
  end

  def destroy
    current_user.user_queries.find_by(query_id: params[:id]).destroy
    redirect_to queries_path
  end

  def update_results_visit
    user_query = UserQuery.find(params[:id])
    user_query.update_attribute(:visited_results_at, Time.zone.now)
  end

  private

    def query_params
      params.permit(:case, :province, :locality, :benefit)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/app_info_helper.rb
module AppInfoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/query_helper.rb
module QueryHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/queries/index.html.erb
<%= content_for :script do %>
  <%= javascript_pack_tag 'force_reload' %>
<% end %>

<div class="header">
  <h2>Wyszukiwania</h2>
</div>

<%= button_to "Nowe wyszukiwanie", queries_new_path, method: :get %>

<div class="box-list">
  <%= render partial: "shared/pagination", locals: { resource: @queries } %>
  <%= render partial: "shared/query", collection: @queries %>
  <%= render partial: "shared/pagination", locals: { resource: @queries } %>
</div>

app/views/queries/new.html.erb
<%= content_for :script do %>
  <%= javascript_pack_tag 'query_submission_spinner' %>
<% end %>

<div class='header'>
  <h2>Nowe wyszukiwanie</h2>
</div>

<% if flash[:warning]%>
  <div class="alert alert-danger" role="alert">
    <%= flash["warning"] %>
  </div>
<% end %>
<br>
<div class="alert alert-info">
  W polu "Świadczenie" należy wpisać nazwę świadczenia (np. "świadczenia z zakresu ortopedii"),<br>
  oddziału (np. "oddział neurologiczny"), poradni (np. "poradnia alergologiczna)<br>
  lub usługi medycznej (np. "rehabilitacja kardiologiczna")
</div>

<%= form_with(url: queries_create_path, method: :post) do |f| %>
  <%= render 'shared/flash_alert' %>
  <div class="form-group">
    <label class="category-select">
      <%= f.check_box :case, {}, 2, 1  %> Pilny przypadek
    </label>
  </div>
  <div class="form-group">
    <%= f.text_field :benefit, placeholder: "Świadczenie" %>
  </div>
  <div class="form-group">
    <%= f.text_field :locality, placeholder: "Miejscowość" %>
  </div>
  <div class="form-group">
    <%= f.select(:province, Query::PROVINCE_CODES.map{ |pc| [ pc[1], pc[0] ] }) %>
  </div>
  <div class="form-group button">
    <input type="submit" name="commit" value="Zapisz" data-disable-with="Zapisz" >
      <span class="spinner-border spinner-border-sm text-primary " role="status" id="submit_spinner"/>
    </input>
  </div>
<% end %>

app/views/queries/result_display.html.erb
<%= content_for :meta do %>
  <meta name="turbolinks-visit-control" content="reload">
<% end %>

<body data-turbolinks="false">

<%= content_for :script do %>
  <script>var id = <%= @user_query.id %></script>
  <%= javascript_pack_tag 'force_reload' %>
  <%= javascript_pack_tag 'set_visit_time' %>
<% end %>

<div class='results-header'>
  <h2>Wyniki wyszukiwania dla zapytania "<%= @query.benefit %>, <%= @query.locality %>, <%= @query.province %>"</h2>
</div>

<% if @query_results.empty? %>

  <p>Dla tego wyszukiwania nie ma w tej chwili żadnych wyników. Damy Ci znać, jeśli się pojawią.<p>
  <br>
  <%= button_to "Powrót", queries_path, method: :get %>

<% else %>

  <div class="box-list">
    <%= render partial: "shared/result", collection: @query_results, locals: { user_query: @user_query } %>
  </div>

  <%= button_to "Powrót", queries_path, method: :get %>

<% end %>